# Update version and changelog, then publish to npm

name: Release

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: node
        uses: actions/setup-node@v2
        env:
          PLAYER_NPM_PUBLISH: ${{ secrets.PLAYER_NPM_PUBLISH }}
        with:
          node-version: '16'
          cache: 'npm'

      - name: Bump version and update CHANGELOG
        working-directory: package
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          npm run release

          npm install --package-lock-only
          git commit --amend --no-edit package-lock.json

          git push --follow-tags origin master
          node -e 'console.log("VERSION=" + require("./package.json").version)' >> $GITHUB_ENV
          
      - name: Publish npm package
        env:
          PLAYER_NPM_PUBLISH: ${{ secrets.PLAYER_NPM_PUBLISH }}
        working-directory: package
        run: |
          npm --version
          echo '_authToken=${PLAYER_NPM_PUBLISH}' > .npmrc
          npm publish
          rm .npmrc
          
      - name: slack-send
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: sdk-releases
          slack-message: |
            New release: [React SDK Release:${{ env.VERSION }}](${{ github.event.release.html_url }})
            Repository: ${{ github.repository }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
